title: SmockSec
description: Cybersecurity Portfolio | SOC | DFIR | Detection Engineering
theme: jekyll-theme-cayman

include:
  - assets

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
